// export { default as MonthlyStats } from './MonthlyStatistics/MonthlyStatistics.svelte'
export { default as NameSection} from './about/NameSection.svelte'
export { default as SkillsSection} from './about/SkillsSection.svelte'
export { default as SkillsContainer} from './about/SkillsContainer.svelte'
export { default as SkillLevelComp} from './about/SkillLevelComp.svelte'
export { default as Appear} from './Appear.svelte'
